### Apple Inc.
GET http://localhost:8000/stocks-market-api/global-quote/AAPL

### Microsoft
GET http://localhost:8000/stocks-market-api/global-quote/MSFT

### Alphabet Inc.
GET http://localhost:8000/stocks-market-api/global-quote/GOOGL

### Amazon
GET http://localhost:8000/stocks-market-api/global-quote/AMZN

### NVIDIA
GET http://localhost:8000/stocks-market-api/global-quote/NVDA

### Meta Platforms
GET http://localhost:8000/stocks-market-api/global-quote/META

### Tesla
GET http://localhost:8000/stocks-market-api/global-quote/TSLA

### Toyota
GET http://localhost:8000/stocks-market-api/global-quote/TM

### ExxonMobil
GET http://localhost:8000/stocks-market-api/global-quote/XOM

### Shell plc
GET http://localhost:8000/stocks-market-api/global-quote/SHEL

### JPMorgan Chase
GET http://localhost:8000/stocks-market-api/global-quote/JPM

### Goldman Sachs
GET http://localhost:8000/stocks-market-api/global-quote/GS

### Visa
GET http://localhost:8000/stocks-market-api/global-quote/V

### Coca-Cola
GET http://localhost:8000/stocks-market-api/global-quote/KO

### PepsiCo
GET http://localhost:8000/stocks-market-api/global-quote/PEP

### Walmart
GET http://localhost:8000/stocks-market-api/global-quote/WMT

### Nike
GET http://localhost:8000/stocks-market-api/global-quote/NKE


### 🇪🇸 España

### Inditex
GET http://localhost:8000/stocks-market-api/global-quote/ITX.MC

### Banco Santander
GET http://localhost:8000/stocks-market-api/global-quote/SAN.MC

### BBVA
GET http://localhost:8000/stocks-market-api/global-quote/BBVA.MC

### Iberdrola
GET http://localhost:8000/stocks-market-api/global-quote/IBE.MC
