### Apple Inc.
GET http://localhost:8000/stock-market-api/quote/AAPL

### Microsoft
GET http://localhost:8000/stock-market-api/quote/MSFT

### Alphabet Inc.
GET http://localhost:8000/stock-market-api/quote/GOOG

### Amazon
GET http://localhost:8000/stock-market-api/quote/AMZN

### NVIDIA
GET http://localhost:8000/stock-market-api/quote/NVDA

### Meta Platforms
GET http://localhost:8000/stock-market-api/quote/META

### Tesla
GET http://localhost:8000/stock-market-api/quote/TSLA

### Toyota
GET http://localhost:8000/stock-market-api/quote/TM

### ExxonMobil
GET http://localhost:8000/stock-market-api/quote/XOM

### Shell plc
GET http://localhost:8000/stock-market-api/quote/SHEL

### JPMorgan Chase
GET http://localhost:8000/stock-market-api/quote/JPM

### Goldman Sachs
GET http://localhost:8000/stock-market-api/quote/GS

### Visa
GET http://localhost:8000/stock-market-api/quote/V

### Coca-Cola
GET http://localhost:8000/stock-market-api/quote/KO

### PepsiCo
GET http://localhost:8000/stock-market-api/quote/PEP

### Walmart
GET http://localhost:8000/stock-market-api/quote/WMT

### Nike
GET http://localhost:8000/stock-market-api/quote/NKE
