services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Mocks\AlphaVantageClientMock: ~

    app.alpha_vantage_client:
        alias: App\Tests\Mocks\AlphaVantageClientMock
        public: true

    App\Domain\AlphaVantage\Client\AlphaVantageClientInterface:
        alias: App\Tests\Mocks\AlphaVantageClientMock
        public: true
