services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Mocks\FinnHubClientMock: ~

    app.finn_hub_client:
        alias: App\Tests\Mocks\FinnHubClientMock
        public: true

    App\Domain\FinnHub\Client\FinnHubClientInterface:
        alias: App\Tests\Mocks\FinnHubClientMock
        public: true
