name: CI

on:
    push:
    pull_request:

jobs:
    quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.4
                  extensions: mbstring, xml, intl, pdo_sqlite

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist

            - name: CS Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run --diff

            - name: PHPStan
              run: vendor/bin/phpstan analyse

            - name: Psalm
              run: vendor/bin/psalm

            - name: Deptrac
              run: vendor/bin/deptrac analyse --report-uncovered

            - name: Rector
              run: vendor/bin/rector process --dry-run

            - name: Tests
              run: vendor/bin/phpunit
